# Generated by Django 5.2 on 2025-05-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=11, unique=True)),
                ('faculty', models.CharField(max_length=100)),
            ],
        ),
    ]
